/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hellonative */

#ifndef _Included_Hellonative
#define _Included_Hellonative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hellonative
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Hellonative_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
